name: Check Conventional Commits format
on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
  merge_group:
    types: [checks_requested]
    
 
permissions:
  pull-requests: write

jobs:
    check-title:
        uses: CQCL/hugrverse-actions/.github/workflows/pr-title.yml@main
        secrets:
            GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    comment-on-pr:
      runs-on: ubuntu-24.04
      permissions:
        pull-requests: write
      steps:
        - name: Comment on Pull Request
          run: |
            gh pr comment --create-if-none --edit-last ${{ github.event.pull_request.number }} \
              --body "Hello and thank you for making a PR to qnexus! :wave:\nA maintainer will review and run integration tests if required."
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}