name: Create Release

on:
  release:
    types: [created]
env:
  UV_VERSION: "0.6.6"

jobs:
  build-and-publish:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up uv & venv
      uses: astral-sh/setup-uv@v5
      with:
        version: ${{ env.UV_VERSION }}
        enable-cache: true
        python-version: 3.12
        cache-dependency-glob: uv.lock
  
    - name: Build
      run: uv build

    - name: Build and Publish to PyPI
      run: uv  publish --token ${{ secrets.PYPI_API_TOKEN }}
